name: Blue Umbrella Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup test environment
        run: npm run test:setup
        env:
          IS_TESTING_MODE: 'true'
      
      - name: Start Next.js development server
        run: |
          npm run dev -- --port 3001 &
          sleep 10
        env:
          IS_TESTING_MODE: 'true'
      
      - name: Run API tests
        run: npm run test:api
        env:
          IS_TESTING_MODE: 'true'
      
      - name: Build Next.js application
        run: npm run build
        env:
          IS_TESTING_MODE: 'true'
